### ISSUE TITLE
Loading data

### ISSUE THREAD

**Issue by thomaskaa** [samthiele/hylite#5]
Hey, any hint to loads sentinel 2 data, 
Thanks for the works,
Thomas

**Comment by samthiele** [comment]
Morning Thomas.

I've not loaded any Sentinel data before, but what file format is it? If it can be loaded by GDAL or spectral python (SPy) then hylite might be able to read it natively. Otherwise you can always load the data into a numpy array using whatever library is convenient and then put it into a highlight image using: 

```
image = hylite.HyImage( my_hypercube_data_array ) # optional: also specify an affine transform using the affine = keyword
image.set_wavelengths( my_hypercube_wavelenght_array )
```
 
 Hope this helps.

**Comment by thomaskaa** [comment]
Thansk for you're answer,
I can have the data in a Geotiff format with the 12 different bands, normaly it can be loaded buy GDAL, 
I read on your papers and also based on the 01_The_basics.ipynb I need, point cloud data's or hypercloud, is it to make a 3D visualisation of the model, can we skip it in your approche ? ? 

Thanks for your suppot

**Comment by samthiele** [comment]
If it is a geotiff and GDAL is installed ( `conda install gdal` ) then you should be able to load the image as follows:

```
from hylite import io
image = io.load( path )
```

And if you don't need to fuse the data with a point cloud then just working with HyImage instances should be fine (meaning no geometric corrections). Atmospheric correction can be quite tricky, but if the data you have is already well corrected then yes - you can skip that step too :-)
